SELECT C.CUS_LNAME, P.P_DESCRIPT, SUM(SALE_UNITS*SALE_PRICE) AS TOTALSALES
FROM

DWDAYSALESFACT AS S
INNER JOIN DWPRODUCT AS P 
ON S.P_CODE = P.P_CODE

INNER JOIN DWCUSTOMER AS C
ON S.CUS_CODE = C.CUS_CODE

GROUP BY ROLLUP (CUS_LNAME, P_DESCRIPT);