SELECT T.TM_MONTH, P.P_CATEGORY, SUM(SALE_UNITS*SALE_PRICE) AS TOTALSALES
FROM

DWDAYSALESFACT AS S
INNER JOIN DWPRODUCT AS P 
ON S.P_CODE = P.P_CODE

INNER JOIN DWTIME AS T
ON T.TM_ID = S.TM_ID

GROUP BY ROLLUP (TM_MONTH, P_CATEGORY);