SELECT TM_MONTH, COUNT(S.SALE_UNITS) AS UNITS_SOLD, SUM(SALE_UNITS*SALE_PRICE) AS TOTALSALES
FROM

DWDAYSALESFACT AS S

INNER JOIN DWTIME AS T
ON T.TM_ID = S.TM_ID

GROUP BY ROLLUP (TM_MONTH);