SELECT TM_MONTH, P.P_CATEGORY, COUNT(S.SALE_UNITS) AS UNITS_SOLD, SUM(SALE_UNITS*SALE_PRICE) AS TOTALSALES
FROM

DWDAYSALESFACT AS S

INNER JOIN DWPRODUCT AS P 
ON S.P_CODE = P.P_CODE

INNER JOIN DWTIME AS T
ON T.TM_ID = S.TM_ID

GROUP BY CUBE (P_CATEGORY, TM_MONTH);