SELECT R.REG_NAME, C.CUS_LNAME, SUM(SALE_UNITS*SALE_PRICE) AS TOTALSALES
FROM

DWDAYSALESFACT AS S

INNER JOIN DWCUSTOMER AS C
ON S.CUS_CODE = C.CUS_CODE

INNER JOIN DWREGION AS R
ON R.REG_ID = C.REG_ID

GROUP BY ROLLUP (REG_NAME, CUS_LNAME);