SELECT   V.V_CODE, P.P_CODE, SUM(SALE_UNITS*SALE_PRICE) AS TOTSALES
FROM     

DWDAYSALESFACT AS S
INNER JOIN DWPRODUCT AS P 
ON S.P_CODE = P.P_CODE

INNER JOIN DWVENDOR AS V 
ON P.V_CODE = V.V_CODE

GROUP BY ROLLUP (V.V_CODE, P.P_CODE)
ORDER BY V.V_CODE, P.P_CODE;