SELECT LGEMPLOYEE.EMP_NUM, LGEMPLOYEE.EMP_LNAME, LGEMPLOYEE.EMP_FNAME, LGSALARY_HISTORY.SAL_AMOUNT
FROM LGEMPLOYEE INNER JOIN LGSALARY_HISTORY ON LGEMPLOYEE.EMP_NUM = LGSALARY_HISTORY.EMP_NUM
WHERE (((LGEMPLOYEE.[DEPT_NUM])=300) AND ((LGSALARY_HISTORY.SAL_END) Is Null))
ORDER BY LGSALARY_HISTORY.SAL_AMOUNT DESC;
