
SELECT LGEMPLOYEE.EMP_NUM, LGEMPLOYEE.EMP_FNAME, LGEMPLOYEE.EMP_LNAME, LGEMPLOYEE.EMP_EMAIL, Sum(LGLINE.LINE_QTY) AS Total
FROM (LGBRAND INNER JOIN LGPRODUCT ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID) INNER JOIN ((LGEMPLOYEE INNER JOIN LGINVOICE ON LGEMPLOYEE.EMP_NUM = LGINVOICE.EMPLOYEE_ID) INNER JOIN LGLINE ON LGINVOICE.INV_NUM = LGLINE.INV_NUM) ON LGPRODUCT.PROD_SKU = LGLINE.PROD_SKU
WHERE (((LGBRAND.BRAND_NAME)='BINDER PRIME') AND ((LGINVOICE.INV_DATE)>='11/1/2011' And (LGINVOICE.INV_DATE)<='12/5/2011'))
GROUP BY LGEMPLOYEE.EMP_NUM, LGEMPLOYEE.EMP_FNAME, LGEMPLOYEE.EMP_LNAME, LGEMPLOYEE.EMP_EMAIL
ORDER BY Sum(LGLINE.LINE_QTY) DESC, LGEMPLOYEE.EMP_LNAME;