SELECT TEMP22A.INV_NUM, TEMP22B.LINE_NUM, TEMP22B.PROD_SKU, TEMP22B.PROD_DESCRIPT, TEMP22A.LINE_NUM, TEMP22A.PROD_SKU, TEMP22A.PROD_DESCRIPT, TEMP22B.BRAND_ID
FROM TEMP22A INNER JOIN TEMP22B ON TEMP22A.INV_NUM = TEMP22B.INV_NUM
WHERE (((TEMP22A.BRAND_ID)=[TEMP22B].[BRAND_ID]))
GROUP BY TEMP22A.INV_NUM, TEMP22B.LINE_NUM, TEMP22B.PROD_SKU, TEMP22B.PROD_DESCRIPT, TEMP22A.LINE_NUM, TEMP22A.PROD_SKU, TEMP22A.PROD_DESCRIPT, TEMP22B.BRAND_ID;