SELECT LGBRAND.BRAND_NAME, LGBRAND.BRAND_TYPE, LGPRODUCT.PROD_SKU, LGPRODUCT.PROD_DESCRIPT, LGPRODUCT.PROD_PRICE
FROM TEMP27, LGBRAND INNER JOIN LGPRODUCT ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
WHERE ((LGPRODUCT.PROD_PRICE)>(TEMP27.MaxOfPROD_PRICE))
GROUP BY LGBRAND.BRAND_NAME, LGBRAND.BRAND_TYPE, LGPRODUCT.PROD_SKU, LGPRODUCT.PROD_DESCRIPT, LGPRODUCT.PROD_PRICE, LGBRAND.BRAND_TYPE
HAVING ((Not (LGBRAND.BRAND_TYPE)='PREMIUM'));