SELECT LGBRAND.BRAND_TYPE, Max(LGPRODUCT.PROD_PRICE) AS MaxOfPROD_PRICE INTO TEMP27
FROM LGBRAND INNER JOIN LGPRODUCT ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
GROUP BY LGBRAND.BRAND_TYPE
HAVING (((LGBRAND.BRAND_TYPE)='PREMIUM'))
ORDER BY Max(LGPRODUCT.PROD_PRICE) DESC;